FROM python:3.5

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ONBUILD COPY requirements.txt /usr/src/app/

ONBUILD RUN pip install --trusted-host pypi.python.org -r requirements.txt

ONBUILD COPY . /usr/src/app

ONBUILD EXPOSE 80

ONBUILD CMD ["python", "app.py"]

